aulavirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blogs.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/urls.py
from django.urls import path
from blogs import views


urlpatterns = [
    path("blogs/", views.BlogList.as_view(), name="blogs_listas"),
    path("blogs2/", views.BlogList2.as_view(), name="blogs_listas2"),
    path("entregar/", views.BlogCreate.as_view(), name="blogs_crear"),
    path("consignas/", views.BlogCreate2.as_view(), name="blogs_consignas"),


    path("detalle/<pk>/", views.BlogDetail.as_view(), name ="blogs_detalles"),
    path("editar/<pk>/", views.BlogUpdate.as_view(), name ="blogs_actualizar"),
    path("borrar/<pk>/", views.BlogDelete.as_view(), name ="blogs_eliminar"),



    path("editar2/<pk>/", views.BlogUpdate2.as_view(), name ="blogs_actualizar2"),
    path("borrar2/<pk>/", views.BlogDelete2.as_view(), name ="blogs_eliminar2"),
    path("detalle2/<pk>/", views.BlogDetail2.as_view(), name ="blogs_detalles2"),

  
  ##  path("entrar/", views.BlogLogin.as_view(), name="blogs_iniciarsesion"),
    path("salir/", views.BlogLogout.as_view(), name="blogs_desconectar"),
    path("about/", views.About.as_view(), name="about" ),
    path("", views.Index.as_view(), name="Index" ),

]

usuario/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from usuario import views

urlpatterns = [
    path("crear/", views.SignUpView.as_view(), name ="usuario_iniciarsesion"),
    path("profile/<pk>/", views.BloggerProfile.as_view(), name ="usuario_perfil"),
    path("editar/<pk>/", views.BloggerUpdate.as_view(), name ="usuario_editar"),
    path("entrar/", views.BlogLogin.as_view(), name="blogs_iniciarsesion"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from operator import truediv
from pyexpat import model
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

class BlogModel2(models.Model):
    profesor = models.CharField(max_length=100)
    materia = models.CharField(max_length=100)
    tarea = models.TextField()
    autor2 = models.ForeignKey(User, on_delete=models.AutoField, null=True)
    fecha_creacion2 = models.DateField(auto_now_add=True)


class BlogModel(models.Model):
    titulo = models.CharField(max_length=100)
    sub_titulo = models.CharField(max_length=100)
    cuerpo = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.AutoField)
    fecha_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo
        

usuario/models.py
from django.db import models
from django.contrib.auth.models import User


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatars", null=True, blank=True)

blogs/views.py
from ast import Index
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from blogs.models import BlogModel, BlogModel2 
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class BlogList(LoginRequiredMixin, ListView):
    login_url = '/usuario/entrar/'
    model = BlogModel
    model2 = User
    template_name = "blogs/blogs_listas.html"   



class BlogDetail(DetailView):

    model = BlogModel
    template_name = "blogs/blogs_detalles.html"


class BlogCreate(LoginRequiredMixin, CreateView):

    model = BlogModel
    success_url = reverse_lazy("blogs_listas")
    fields = ["titulo", "sub_titulo", "cuerpo"]
    readonly_fields = ['created', "fecha_creacion"]

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)


class BlogUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = BlogModel
    success_url = reverse_lazy("blogs_listas")
    fields = ["titulo", "sub_titulo", "cuerpo" ]
    readonly_fields = ["fecha_creacion"]

    def test_func(self):
        exist = BlogModel.objects.filter(autor=self.request.user.id, id=self.kwargs['pk'])
        return True if exist else False








class BlogList2(LoginRequiredMixin, ListView):
    login_url = '/usuario/entrar/'
    model = BlogModel2
    template_name = "blogs/blogmodel2_list.html"          

class BlogCreate2(LoginRequiredMixin, CreateView):

    model = BlogModel2
    success_url = reverse_lazy("blogs_listas2")
    fields = ["profesor", "materia", "tarea"]
    readonly_fields = ['created', "fecha_creacion2"]

    def form_valid(self, form):
        form.instance.autor2 = self.request.user
        return super().form_valid(form)

        
class BlogUpdate2(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = BlogModel2
    success_url = reverse_lazy("blogs_listas2")
    fields = ["profesor", "materia", "tarea" ]
    readonly_fields = ["fecha_creacion2"]

    def test_func(self):
        exist = BlogModel2.objects.filter(autor2=self.request.user.id, id=self.kwargs['pk'])
        return True if exist else False



class BlogDelete2(LoginRequiredMixin,UserPassesTestMixin, DeleteView):

    model = BlogModel2
    success_url = reverse_lazy("blogs_listas2")

    def test_func(self):
        exist = BlogModel2.objects.filter(autor2=self.request.user.id, id=self.kwargs['pk'])
        return True if exist else False



class BlogDetail2(DetailView):

    model = BlogModel2
    template_name = "blogs/blogs_detalles2.html"











        

class BlogDelete(LoginRequiredMixin,UserPassesTestMixin, DeleteView):

    model = BlogModel
    success_url = reverse_lazy("blogs_listas")

    def test_func(self):
        exist = BlogModel.objects.filter(autor=self.request.user.id, id=self.kwargs['pk'])
        return True if exist else False


class BlogLogin(LoginView):
    template_name = 'blogs/blogs_iniciarsesion.html'
    next_page = reverse_lazy("blogs_listas")


class BlogLogout(LogoutView):
    template_name = 'blogs/blogs_desconectar.html'
    

class About(LoginRequiredMixin, ListView):
    login_url = '/usuario/entrar/'
    model = BlogModel
    template_name = "blogs/about.html"

class Index(ListView):
    model = BlogModel
    template_name = 'blogs/index.html'

usuario/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, UpdateView, DetailView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User


class SignUpView(SuccessMessageMixin, CreateView):
  template_name = 'usuario/usuario_crear_cuenta_form.html'
  success_url = reverse_lazy('blogs_iniciarsesion')
  form_class = UserCreationForm
  success_message = "¡¡ Se creo tu perfil satisfactoriamente !!"

class BloggerProfile(DetailView):

    model = User
    template_name = "usuario/usuario_detalle.html"


class BloggerUpdate(LoginRequiredMixin, UpdateView):

    model = User
    template_name = "usuario/usuario_form.html"
    fields = ["username", "email", "first_name", "last_name"]

    def get_success_url(self):
      return reverse_lazy("usuario_perfil", kwargs={"pk": self.request.user.id})

class BlogLogin(LoginView):
    template_name = 'blogs/blogs_iniciarsesion.html'
    next_page = reverse_lazy("blogs_listas") 

blogs/templates/blogs/about.html
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{%load static%}
<html>
<head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/listas.css' %}">
    <div class="container-fluid justify-content-between">
      <div class="d-flex">
        <a class="navbar-brand me-2 mb-1 d-flex align-items-center" href="">
          <img
            src="https://i.postimg.cc/Z5FDD5vZ/pngwing-com.png"
            height="80"
            alt=""
            loading="lazy"
            style="margin-top: -10px;"
          />
        </a>
        
        <ul class ="nav navbar-nav">
          <li class ="nav-item">
            <a href="{%url  'blogs_consignas' %}" class="btn btn-lg btn-default">Profesor, cree una nueva actividad</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_crear' %}" class="btn btn-lg btn-default">Alumno, entregue su tarea</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_listas2' %}" class="btn btn-lg btn-default">Vea las actividades subidas</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_listas' %}" class="btn btn-lg btn-default">Vea las tareas subidas</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'about' %}" class="btn btn-lg btn-default">About</a>
          </li>
          
          </ul>
      </div>


      
      <ul class="navbar-nav flex-row">
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link d-sm-flex align-items-sm-center">
            <img>
            <strong class="d-none d-sm-block ms-1">{{user.username}}</strong> </a> 
            {% if user.avatar_set.first.image.url %}
            <img class="card-img" height="50" src="{{ user.avatar_set.first.image.url }}" />
            {% else %}
            <img class="card-img" height="50" width="" src="{% static 'blogs/css/default.png' %}" />
            {% endif %}
          </a>
        </li>
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link" href="#">
            <span><i class="fas fa-plus-circle fa-lg"></i></span>
          </a>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1">
          <a
            class="nav-link  hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fas fa-comments fa-lg"></i>
            <a class="btn btn-outline-secondary" href="{% url 'usuario_editar' user.id %}"> Config </a><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-gear-512.png" alt="" height="23"></button>
          
          </a>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1">
          <a
            class="nav-link  hidden-arrow"
            href="/"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fas fa-bell fa-lg"></i>
            <a class="btn btn-outline-secondary" href="{% url 'blogs_desconectar' %}"> Logout </a>

          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
        </li>
      </ul>
    </div>
  </nav>
</head>
<body>
  
  <p>
    Esta pagina web fue realizada para el curso de Python en la plataforma de CoderHouse a modo de entrega final.
    <br>
    Creamos esta pagina con el fin de que profesores creen actividades y que alumnos puedan responder a ellas posteando sus resoluciones.
    <br>
    Creada por Agustin Fassetta, Agustin Pelle y Agustin Neme.
  </p>

  <footer><footer class="bg-dark text-center text-white">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(171, 185, 192, 0.603);">
      © 2022 Copyright:
      <a class="text-white"</a>
    </div>
    <!-- Copyright -->
  </footer>
</body>
</html>

blogs/templates/blogs/blogmodel2_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>¿Está Seguro que quiere eliminar la tarea?</p>
    {{ form }}
    <input type="submit" value="Confirmar">
</form>

blogs/templates/blogs/blogmodel2_form.html
{%load static%}

<a href="{% url 'blogs_listas2' %}">Volver a Lista</a>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/model.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>
       
</body>
</html>

blogs/templates/blogs/blogmodel2_list.html
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
<html>
<head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/listas.css' %}">
    <div class="container-fluid justify-content-between">
      <div class="d-flex">
        <a class="navbar-brand me-2 mb-1 d-flex align-items-center" href="">
          <img
            src="https://i.postimg.cc/Z5FDD5vZ/pngwing-com.png"
            height="80"
            alt=""
            loading="lazy"
            style="margin-top: -10px;"
          />
        </a>
        
        <ul class ="nav navbar-nav">
          <li class ="nav-item">
            <a href="{%url  'blogs_consignas' %}" class="btn btn-lg btn-default">Profesor, cree una nueva actividad</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_crear' %}" class="btn btn-lg btn-default">Alumno, entregue su tarea</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_listas2' %}" class="btn btn-lg btn-default">Vea las actividades subidas</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_listas' %}" class="btn btn-lg btn-default">Vea las tareas subidas</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'about' %}" class="btn btn-lg btn-default">About</a>
          </li>
          
          </ul>
      </div>


      
      <ul class="navbar-nav flex-row">
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link d-sm-flex align-items-sm-center">
            <img>
            <strong class="d-none d-sm-block ms-1">{{user.username}}</strong> </a> 
            {% if user.avatar_set.first.image.url %}
            <img class="card-img" height="50" src="{{ user.avatar_set.first.image.url }}" />
            {% else %}
            <img class="card-img" height="50" width="" src="{% static 'blogs/css/default.png' %}" />
            {% endif %}
          </a>
        </li>
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link" href="#">
            <span><i class="fas fa-plus-circle fa-lg"></i></span>
          </a>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1">
          <a
            class="nav-link  hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fas fa-comments fa-lg"></i>
            <a class="btn btn-outline-secondary" href="{% url 'usuario_editar' user.id %}"> Config </a><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-gear-512.png" alt="" height="23"></button>
          
          </a>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1">
          <a
            class="nav-link  hidden-arrow"
            href="/"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fas fa-bell fa-lg"></i>
            <a class="btn btn-outline-secondary" href="{% url 'blogs_desconectar' %}"> Logout </a>

          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
        </li>
      </ul>

    </div>
  </nav>
</head>

{% if object_list %}
    {% for blog in object_list %}

    <li>
        <a href="{% url 'blogs_detalles2' blog.id %}">{{blog.profesor}}</a>
        {% if user.is_authenticated %}
        <a href="{% url 'blogs_eliminar2' blog.id %}">Borrar</a>
        <a href="{% url 'blogs_actualizar2' blog.id %}">Actualizar</a>
          
        {% endif %}

    </li>
    {% endfor %}
{% else %}

  <h1> No hay actividades subidas</h1>
{% endif %}

<body>
  <footer><footer class="bg-dark text-center text-white">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(171, 185, 192, 0.603);">
      © 2022 Copyright:
      <a class="text-white"</a>
    </div>
    <!-- Copyright -->
  </footer>
</body>

</html>

blogs/templates/blogs/blogmodel_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>¿Está Seguro que quiere eliminar "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirmar">
</form>

blogs/templates/blogs/blogmodel_form.html
{%load static%}

<a href="{% url 'blogs_listas' %}">Volver a Lista</a>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/model.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>
       
</body>
</html>

blogs/templates/blogs/blogs_desconectar.html
{% extends "blogs/front.html" %}
{% load static %}

{% block cuerpo %}
<body>
    <div class="container">
        <ul class="nav justify-content-center ">
        <div style="width:1000px; margin: 276.5px auto;">
        <div class="starter-template">
        <center>

        <h1>Te deslogueaste con exito! </h1>
        <br>------------------------------------------------------------------------------------------------</br>
           <br></br>
        <h3></h3>
        
         <div style="width:1000px; margin:30 auto;">
                    
         <a class="btn btn-outline-primary btn-lg" href="{%url  'usuario_iniciarsesion' %}" role="button">Sign Up</a>
                   
         <a class="btn btn-outline-primary btn-lg" href="{%url  'blogs_iniciarsesion' %}" role="button">Login</a>
                   
          </div>
        </center>
        </div>
        </div>
      </div>
<script>
// Redirecciona al Index principal
  window.setTimeout(function() {
  window.location.href = '/';
  }, 2000); //    2000 MS = 2 SEGUNDOS
</script>

{% endblock %}

blogs/templates/blogs/blogs_detalles.html
{%load static%}
<a href="{% url 'blogs_listas' %}">Volver a Lista</a>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/model.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>{{object.titulo}}</h1>
        <h2>{{object.sub_titulo}}</h2>
        <p> {{object.cuerpo}} </p>
        <h3> Entregado el dia: {{object.fecha_creacion}}</h3>
        <p>Esta tarea ha sido creada por <strong>{{object.autor}}</strong></p>
    </div>
</body>
</html>

blogs/templates/blogs/blogs_detalles2.html
{%load static%}
<a href="{% url 'blogs_listas' %}">Volver a Lista</a>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/model.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>{{object.profesor}}</h1>
        <h2>{{object.materia}}</h2>
        <p> {{object.tarea}} </p>
        <h3> Entregado el dia: {{object.fecha_creacion2}}</h3>
        <p>Esta tarea ha sido creada por <strong>{{object.autor2}}</strong></p>
    </div>
    
    
</body>
</html>

blogs/templates/blogs/blogs_iniciarsesion.html
{% extends "blogs/front.html" %}
{% load static %}


{% block cuerpo %}
<div style="width:1000px; margin: 289.5px auto;">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button  href="{%url  'blogs_listas' %}" type="submit">Iniciar Sesión</button>
    <a href="{%url  'usuario_iniciarsesion' %}" role="button">Registrarte</a>
</form>
</div>
{% endblock %}

blogs/templates/blogs/blogs_listas.html
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
<html>
<head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/listas.css' %}">
  
    <div class="container-fluid justify-content-between">
      <div class="d-flex">
        <a class="navbar-brand me-2 mb-1 d-flex align-items-center" href="">
          <img
            src="https://i.postimg.cc/Z5FDD5vZ/pngwing-com.png"
            height="80"
            alt=""
            loading="lazy"
            style="margin-top: -10px;"
          />
        </a>
        
        <ul class ="nav navbar-nav">
          <li class ="nav-item">
            <a href="{%url  'blogs_consignas' %}" class="btn btn-lg btn-default">Profesor, cree una nueva actividad</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_crear' %}" class="btn btn-lg btn-default">Alumno, entregue su tarea</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_listas2' %}" class="btn btn-lg btn-default">Vea las actividades subidas</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'blogs_listas' %}" class="btn btn-lg btn-default">Vea las tareas subidas</a>
          </li>

          <li class ="nav-item">
            <a href="{% url 'about' %}" class="btn btn-lg btn-default">About</a>
          </li>
          
          </ul>
      </div>


      
      <ul class="navbar-nav flex-row">
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link d-sm-flex align-items-sm-center">
            <img>
            <strong class="d-none d-sm-block ms-1">{{user.username}}</strong> </a> 
            {% if user.avatar_set.first.image.url %}
            <img class="card-img" height="50" src="{{ user.avatar_set.first.image.url }}" />
            {% else %}
            <img class="card-img" height="50" width="50" src="{% static 'blogs/css/default.png' %}" />
            {% endif %}
          </a>
        </li>
        <li class="nav-item me-3 me-lg-1">
          <a class="nav-link" href="#">
            <span><i class="fas fa-plus-circle fa-lg"></i></span>
          </a>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1">
          <a
            class="nav-link  hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fas fa-comments fa-lg"></i>
            <a class="btn btn-outline-secondary" href="{% url 'usuario_editar' user.id %}"> Config </a><img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-gear-512.png" alt="" height="23"></button>
          
          </a>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1">
          <a
            class="nav-link  hidden-arrow"
            href="/"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fas fa-bell fa-lg"></i>
            <a class="btn btn-outline-secondary" href="{% url 'blogs_desconectar' %}"> Logout </a>

          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
        </li>
      </ul>

    </div>
  </nav>
</head>

{% if object_list %}
    {% for blog in object_list %}

    <li>
        <a href="{% url 'blogs_detalles' blog.id %}">{{blog.titulo}}</a>
      
        {% if user.is_authenticated %}
        <a href="{% url 'blogs_eliminar' blog.id %}">Borrar</a>
        <a href="{% url 'blogs_actualizar' blog.id %}">Actualizar</a>
          
        {% endif %}

    </li>
    {% endfor %}
{% else %}
  <h1> No hay tareas subidas</h1>
{% endif %}
<body>
  <footer><footer class="bg-dark text-center text-white">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(171, 185, 192, 0.603);">
      © 2022 Copyright:
      <a class="text-white"</a>
    </div>
    <!-- Copyright -->
  </footer>
</body>
</html>

usuario/templates/usuario/usuario_detalle.html
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <link type="text/css" rel="stylesheet" href="{% static 'blogs/css/model.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'blogs_listas' %}">Volver a Lista Blogs</a>
<a href="{% url 'usuario_editar' user.id %}">Editar Perfil</a>

<ul>
    <li>Nombre: {{object.first_name}}</li>
    <li>Apellido: {{object.last_name}}</li>
    <li>Correo electronico: {{object.email}} </li>
    <li>Nombre de Usuario: {{object.username}}</li>
</ul>

{% if user.avatar_set.first.image.url %}
<img class="card-img" height="50" src="{{ user.avatar_set.first.image.url }}" />
{% else %}
<img class="card-img" height="-800" width="100" src="{% static 'blogs/css/default.png' %}" />
{% endif %}
</body>

</html>